/*
 * JournDoc Downloader Client API
 * This is a journdoc downloader client
 *
 * OpenAPI spec version: 1.0.0
 * Contact: david@dskow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.dskow.downloader.models.client;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * FetchResultC
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-26T09:41:10.684-04:00")
public class FetchResultC {
	@SerializedName("PubmedArticleSetC")
	private PubmedArticleSetC pubmedArticleSet = null;

	public FetchResultC pubmedArticleSet(PubmedArticleSetC pubmedArticleSet) {
		this.pubmedArticleSet = pubmedArticleSet;
		return this;
	}

	/**
	 * A header
	 * 
	 * @return pubmedArticleSet
	 **/
	@ApiModelProperty(example = "null", value = "A header")
	public PubmedArticleSetC getPubmedArticleSetCC() {
		return pubmedArticleSet;
	}

	public void setPubmedArticleSetCC(PubmedArticleSetC pubmedArticleSet) {
		this.pubmedArticleSet = pubmedArticleSet;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		FetchResultC fetchResultC = (FetchResultC) o;
		return Objects.equals(this.pubmedArticleSet, fetchResultC.pubmedArticleSet);
	}

	@Override
	public int hashCode() {
		return Objects.hash(pubmedArticleSet);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class FetchResultC {\n");

		sb.append("    pubmedArticleSet: ").append(toIndentedString(pubmedArticleSet)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
