/*
 * JournDoc Downloader Client API
 * This is a journdoc downloader client
 *
 * OpenAPI spec version: 1.0.0
 * Contact: david@dskow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.dskow.downloader.models.client;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * FetchErrorListC
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-26T09:41:10.684-04:00")
public class FetchErrorListC {
	@SerializedName("phrasesnotfound")
	private List<String> phrasesnotfound = new ArrayList<String>();

	@SerializedName("fieldsnotfound")
	private List<String> fieldsnotfound = new ArrayList<String>();

	public FetchErrorListC phrasesnotfound(List<String> phrasesnotfound) {
		this.phrasesnotfound = phrasesnotfound;
		return this;
	}

	public FetchErrorListC addPhrasesnotfoundItem(String phrasesnotfoundItem) {
		this.phrasesnotfound.add(phrasesnotfoundItem);
		return this;
	}

	/**
	 * The fetch error phrases not found
	 * 
	 * @return phrasesnotfound
	 **/
	@ApiModelProperty(example = "null", value = "The fetch error phrases not found")
	public List<String> getPhrasesnotfound() {
		return phrasesnotfound;
	}

	public void setPhrasesnotfound(List<String> phrasesnotfound) {
		this.phrasesnotfound = phrasesnotfound;
	}

	public FetchErrorListC fieldsnotfound(List<String> fieldsnotfound) {
		this.fieldsnotfound = fieldsnotfound;
		return this;
	}

	public FetchErrorListC addFieldsnotfoundItem(String fieldsnotfoundItem) {
		this.fieldsnotfound.add(fieldsnotfoundItem);
		return this;
	}

	/**
	 * The fetch error fields not found
	 * 
	 * @return fieldsnotfound
	 **/
	@ApiModelProperty(example = "null", value = "The fetch error fields not found")
	public List<String> getFieldsnotfound() {
		return fieldsnotfound;
	}

	public void setFieldsnotfound(List<String> fieldsnotfound) {
		this.fieldsnotfound = fieldsnotfound;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		FetchErrorListC fetchErrorListC = (FetchErrorListC) o;
		return Objects.equals(this.phrasesnotfound, fetchErrorListC.phrasesnotfound)
				&& Objects.equals(this.fieldsnotfound, fetchErrorListC.fieldsnotfound);
	}

	@Override
	public int hashCode() {
		return Objects.hash(phrasesnotfound, fieldsnotfound);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class FetchErrorListC {\n");

		sb.append("    phrasesnotfound: ").append(toIndentedString(phrasesnotfound)).append("\n");
		sb.append("    fieldsnotfound: ").append(toIndentedString(fieldsnotfound)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
