/*
 * JournDoc Downloader Client API
 * This is a journdoc downloader client
 *
 * OpenAPI spec version: 1.0.0
 * Contact: david@dskow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.dskow.downloader.models.client;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * FetchWarningListC
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-26T09:41:10.684-04:00")
public class FetchWarningListC {
	@SerializedName("phrasesignored")
	private List<String> phrasesignored = new ArrayList<String>();

	@SerializedName("quotedphrasesnotfound")
	private List<String> quotedphrasesnotfound = new ArrayList<String>();

	@SerializedName("outputmessages")
	private List<String> outputmessages = new ArrayList<String>();

	public FetchWarningListC phrasesignored(List<String> phrasesignored) {
		this.phrasesignored = phrasesignored;
		return this;
	}

	public FetchWarningListC addPhrasesignoredItem(String phrasesignoredItem) {
		this.phrasesignored.add(phrasesignoredItem);
		return this;
	}

	/**
	 * The fetch warning phrases ignored
	 * 
	 * @return phrasesignored
	 **/
	@ApiModelProperty(example = "null", value = "The fetch warning phrases ignored")
	public List<String> getPhrasesignored() {
		return phrasesignored;
	}

	public void setPhrasesignored(List<String> phrasesignored) {
		this.phrasesignored = phrasesignored;
	}

	public FetchWarningListC quotedphrasesnotfound(List<String> quotedphrasesnotfound) {
		this.quotedphrasesnotfound = quotedphrasesnotfound;
		return this;
	}

	public FetchWarningListC addQuotedphrasesnotfoundItem(String quotedphrasesnotfoundItem) {
		this.quotedphrasesnotfound.add(quotedphrasesnotfoundItem);
		return this;
	}

	/**
	 * The fetch warning quoted phrases not found
	 * 
	 * @return quotedphrasesnotfound
	 **/
	@ApiModelProperty(example = "null", value = "The fetch warning quoted phrases not found")
	public List<String> getQuotedphrasesnotfound() {
		return quotedphrasesnotfound;
	}

	public void setQuotedphrasesnotfound(List<String> quotedphrasesnotfound) {
		this.quotedphrasesnotfound = quotedphrasesnotfound;
	}

	public FetchWarningListC outputmessages(List<String> outputmessages) {
		this.outputmessages = outputmessages;
		return this;
	}

	public FetchWarningListC addOutputmessagesItem(String outputmessagesItem) {
		this.outputmessages.add(outputmessagesItem);
		return this;
	}

	/**
	 * The fetch warning output messages
	 * 
	 * @return outputmessages
	 **/
	@ApiModelProperty(example = "null", value = "The fetch warning output messages")
	public List<String> getOutputmessages() {
		return outputmessages;
	}

	public void setOutputmessages(List<String> outputmessages) {
		this.outputmessages = outputmessages;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		FetchWarningListC fetchWarningListC = (FetchWarningListC) o;
		return Objects.equals(this.phrasesignored, fetchWarningListC.phrasesignored)
				&& Objects.equals(this.quotedphrasesnotfound, fetchWarningListC.quotedphrasesnotfound)
				&& Objects.equals(this.outputmessages, fetchWarningListC.outputmessages);
	}

	@Override
	public int hashCode() {
		return Objects.hash(phrasesignored, quotedphrasesnotfound, outputmessages);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class FetchWarningListC {\n");

		sb.append("    phrasesignored: ").append(toIndentedString(phrasesignored)).append("\n");
		sb.append("    quotedphrasesnotfound: ").append(toIndentedString(quotedphrasesnotfound)).append("\n");
		sb.append("    outputmessages: ").append(toIndentedString(outputmessages)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
