/*
 * JournDoc Downloader Client API
 * This is a journdoc downloader client
 *
 * OpenAPI spec version: 1.0.0
 * Contact: david@dskow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.dskow.downloader.models.client;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * FetchResultItemC
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-26T09:41:10.684-04:00")
public class FetchResultItemC {
	@SerializedName("filename")
	private String filename = null;

	@SerializedName("data")
	private String data = null;

	public FetchResultItemC filename(String filename) {
		this.filename = filename;
		return this;
	}

	/**
	 * A filename
	 * 
	 * @return filename
	 **/
	@ApiModelProperty(example = "null", value = "A filename")
	public String getFilename() {
		return filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public FetchResultItemC data(String data) {
		this.data = data;
		return this;
	}

	/**
	 * The search data
	 * 
	 * @return data
	 **/
	@ApiModelProperty(example = "null", value = "The search data")
	public String getData() {
		return data;
	}

	public void setData(String data) {
		this.data = data;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		FetchResultItemC fetchResultItemC = (FetchResultItemC) o;
		return Objects.equals(this.filename, fetchResultItemC.filename)
				&& Objects.equals(this.data, fetchResultItemC.data);
	}

	@Override
	public int hashCode() {
		return Objects.hash(filename, data);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class FetchResultItemC {\n");

		sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
		sb.append("    data: ").append(toIndentedString(data)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
