/*
 * JournDoc Downloader Client API
 * This is a journdoc downloader client
 *
 * OpenAPI spec version: 1.0.0
 * Contact: david@dskow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.dskow.downloader.models.client;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * HeaderC
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-26T09:41:10.684-04:00")
public class HeaderC {
	@SerializedName("type")
	private String type = null;

	@SerializedName("version")
	private String version = null;

	public HeaderC type(String type) {
		this.type = type;
		return this;
	}

	/**
	 * A fetch type
	 * 
	 * @return type
	 **/
	@ApiModelProperty(example = "null", value = "A fetch type")
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public HeaderC version(String version) {
		this.version = version;
		return this;
	}

	/**
	 * A fetch version
	 * 
	 * @return version
	 **/
	@ApiModelProperty(example = "null", value = "A fetch version")
	public String getVersion() {
		return version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		HeaderC headerC = (HeaderC) o;
		return Objects.equals(this.type, headerC.type) && Objects.equals(this.version, headerC.version);
	}

	@Override
	public int hashCode() {
		return Objects.hash(type, version);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class HeaderC {\n");

		sb.append("    type: ").append(toIndentedString(type)).append("\n");
		sb.append("    version: ").append(toIndentedString(version)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
