/*
 * JournDoc Downloader Client API
 * This is a journdoc downloader client
 *
 * OpenAPI spec version: 1.0.0
 * Contact: david@dskow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.dskow.downloader.models.client;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * HistoryC
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-26T09:41:10.684-04:00")
public class HistoryC {
	@SerializedName("PubMedPubDate")
	private List<PubMedPubDateItemC>  pubMedPubDate = new ArrayList<>();

	public HistoryC pubMedPubDate(List<PubMedPubDateItemC> pubMedPubDate) {
		this.pubMedPubDate = pubMedPubDate;
		return this;
	}

	/**
	 * A header
	 * 
	 * @return pubMedPubDate
	 **/
	@ApiModelProperty(example = "null", value = "A header")
	public List<PubMedPubDateItemC> getHistory() {
		return pubMedPubDate;
	}

	public void addPubMedPubDateItem(PubMedPubDateItemC pubMedPubDate) {
		this.pubMedPubDate.add(pubMedPubDate);
	}

	public void setPubMedPubDateItem(List<PubMedPubDateItemC> pubMedPubDate) {
		this.pubMedPubDate = pubMedPubDate;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		HistoryC historyC = (HistoryC) o;
		return Objects.equals(this.pubMedPubDate, historyC.pubMedPubDate);
	}

	@Override
	public int hashCode() {
		return Objects.hash(pubMedPubDate);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class HistoryC {\n");

		sb.append("    pubMedPubDate: ").append(toIndentedString(pubMedPubDate)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
