/*
 * JournDoc Downloader Client API
 * This is a journdoc downloader client
 *
 * OpenAPI spec version: 1.0.0
 * Contact: david@dskow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.dskow.downloader.models.client;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * KeywordListC
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-26T09:41:10.684-04:00")
public class KeywordListC {
	@SerializedName("-Owner")
	private String owner = null;

	@SerializedName("Keyword")
	private KeywordC keyword = null;

	public KeywordListC owner(String owner) {
		this.owner = owner;
		return this;
	}

	/**
	 * A header
	 * 
	 * @return owner
	 **/
	@ApiModelProperty(example = "null", value = "A header")
	public String getOwner() {
		return owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	public KeywordListC keyword(KeywordC keyword) {
		this.keyword = keyword;
		return this;
	}

	/**
	 * A header
	 * 
	 * @return keyword
	 **/
	@ApiModelProperty(example = "null", value = "A header")
	public KeywordC getKeyword() {
		return keyword;
	}

	public void setKeyword(KeywordC keyword) {
		this.keyword = keyword;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		KeywordListC keywordListC = (KeywordListC) o;
		return Objects.equals(this.owner, keywordListC.owner) && Objects.equals(this.keyword, keywordListC.keyword);
	}

	@Override
	public int hashCode() {
		return Objects.hash(owner, keyword);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class KeywordListC {\n");

		sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
		sb.append("    keyword: ").append(toIndentedString(keyword)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
