/*
 * JournDoc Downloader Client API
 * This is a journdoc downloader client
 *
 * OpenAPI spec version: 1.0.0
 * Contact: david@dskow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.dskow.downloader.models.client;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * MedlineCitationC
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-26T09:41:10.684-04:00")
@XmlRootElement(name = "medlineCitation")
@XmlAccessorType(XmlAccessType.FIELD)
public class MedlineCitationC {
	@SerializedName("-Status")
	private String status = null;

	@SerializedName("-Owner")
	private String owner = null;

	@SerializedName("PMID")
	private PMIDC PMID = null;

	@SerializedName("DateCreated")
	private DateItemC dateCreated = null;

	@SerializedName("DateCompleted")
	private DateItemC dateCompleted = null;

	@SerializedName("DateRevised")
	private DateItemC dateRevised = null;

	@SerializedName("Article")
	private ArticleC article = null;

	@SerializedName("MedlineJournalInfo")
	private MedlineJournalInfoC medlineJournalInfo = null;

	@SerializedName("CitationSubset")
	private List<String> citationSubset = new ArrayList<String>();

	@SerializedName("MeshHeadingList")
	private MeshHeadingListC meshHeadingList = null;

	@SerializedName("KeywordList")
	private KeywordListC keywordList = null;

	public MedlineCitationC status(String status) {
		this.status = status;
		return this;
	}

	/**
	 * A header
	 * 
	 * @return status
	 **/
	@ApiModelProperty(example = "null", value = "A header")
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public MedlineCitationC owner(String owner) {
		this.owner = owner;
		return this;
	}

	/**
	 * A header
	 * 
	 * @return owner
	 **/
	@ApiModelProperty(example = "null", value = "A header")
	public String getOwner() {
		return owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	public MedlineCitationC PMID(PMIDC PMID) {
		this.PMID = PMID;
		return this;
	}

	/**
	 * A header
	 * 
	 * @return PMID
	 **/
	@ApiModelProperty(example = "null", value = "A header")
	public PMIDC getPMID() {
		return PMID;
	}

	public void setPMID(PMIDC PMID) {
		this.PMID = PMID;
	}

	public MedlineCitationC dateCreated(DateItemC dateCreated) {
		this.dateCreated = dateCreated;
		return this;
	}

	/**
	 * A header
	 * 
	 * @return dateCreated
	 **/
	@ApiModelProperty(example = "null", value = "A header")
	public DateItemC getDateCreated() {
		return dateCreated;
	}

	public void setDateCreated(DateItemC dateCreated) {
		this.dateCreated = dateCreated;
	}

	public MedlineCitationC dateCompleted(DateItemC dateCompleted) {
		this.dateCompleted = dateCompleted;
		return this;
	}

	/**
	 * A header
	 * 
	 * @return dateCompleted
	 **/
	@ApiModelProperty(example = "null", value = "A header")
	public DateItemC getDateCompleted() {
		return dateCompleted;
	}

	public void setDateCompleted(DateItemC dateCompleted) {
		this.dateCompleted = dateCompleted;
	}

	public MedlineCitationC dateRevised(DateItemC dateRevised) {
		this.dateRevised = dateRevised;
		return this;
	}

	/**
	 * A header
	 * 
	 * @return dateRevised
	 **/
	@ApiModelProperty(example = "null", value = "A header")
	public DateItemC getDateRevised() {
		return dateRevised;
	}

	public void setDateRevised(DateItemC dateRevised) {
		this.dateRevised = dateRevised;
	}

	public MedlineCitationC article(ArticleC article) {
		this.article = article;
		return this;
	}

	/**
	 * A header
	 * 
	 * @return article
	 **/
	@ApiModelProperty(example = "null", value = "A header")
	public ArticleC getArticle() {
		return article;
	}

	public void setArticle(ArticleC article) {
		this.article = article;
	}

	public MedlineCitationC medlineJournalInfo(MedlineJournalInfoC medlineJournalInfo) {
		this.medlineJournalInfo = medlineJournalInfo;
		return this;
	}

	/**
	 * A header
	 * 
	 * @return medlineJournalInfo
	 **/
	@ApiModelProperty(example = "null", value = "A header")
	public MedlineJournalInfoC getMedlineJournalInfo() {
		return medlineJournalInfo;
	}

	public void setMedlineJournalInfo(MedlineJournalInfoC medlineJournalInfo) {
		this.medlineJournalInfo = medlineJournalInfo;
	}

	public MedlineCitationC citationSubset(List<String> citationSubset) {
		this.citationSubset = citationSubset;
		return this;
	}

	public MedlineCitationC addCitationSubsetItem(String citationSubsetItem) {
		this.citationSubset.add(citationSubsetItem);
		return this;
	}

	/**
	 * The fetch warning quoted phrases not found
	 * 
	 * @return citationSubset
	 **/
	@ApiModelProperty(example = "null", value = "The fetch warning quoted phrases not found")
	public List<String> getCitationSubset() {
		return citationSubset;
	}

	public void setCitationSubset(List<String> citationSubset) {
		this.citationSubset = citationSubset;
	}

	public MedlineCitationC meshHeadingList(MeshHeadingListC meshHeadingList) {
		this.meshHeadingList = meshHeadingList;
		return this;
	}

	/**
	 * A header
	 * 
	 * @return meshHeadingList
	 **/
	@ApiModelProperty(example = "null", value = "A header")
	public MeshHeadingListC getMeshHeadingList() {
		return meshHeadingList;
	}

	public void setMeshHeadingList(MeshHeadingListC meshHeadingList) {
		this.meshHeadingList = meshHeadingList;
	}

	public MedlineCitationC keywordList(KeywordListC keywordList) {
		this.keywordList = keywordList;
		return this;
	}

	/**
	 * A header
	 * 
	 * @return keywordList
	 **/
	@ApiModelProperty(example = "null", value = "A header")
	public KeywordListC getKeywordList() {
		return keywordList;
	}

	public void setKeywordList(KeywordListC keywordList) {
		this.keywordList = keywordList;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		MedlineCitationC medlineCitationC = (MedlineCitationC) o;
		return Objects.equals(this.status, medlineCitationC.status)
				&& Objects.equals(this.owner, medlineCitationC.owner)
				&& Objects.equals(this.PMID, medlineCitationC.PMID)
				&& Objects.equals(this.dateCreated, medlineCitationC.dateCreated)
				&& Objects.equals(this.dateCompleted, medlineCitationC.dateCompleted)
				&& Objects.equals(this.dateRevised, medlineCitationC.dateRevised)
				&& Objects.equals(this.article, medlineCitationC.article)
				&& Objects.equals(this.medlineJournalInfo, medlineCitationC.medlineJournalInfo)
				&& Objects.equals(this.citationSubset, medlineCitationC.citationSubset)
				&& Objects.equals(this.meshHeadingList, medlineCitationC.meshHeadingList)
				&& Objects.equals(this.keywordList, medlineCitationC.keywordList);
	}

	@Override
	public int hashCode() {
		return Objects.hash(status, owner, PMID, dateCreated, dateCompleted, dateRevised, article, medlineJournalInfo,
				citationSubset, meshHeadingList, keywordList);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class MedlineCitationC {\n");

		sb.append("    status: ").append(toIndentedString(status)).append("\n");
		sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
		sb.append("    PMID: ").append(toIndentedString(PMID)).append("\n");
		sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
		sb.append("    dateCompleted: ").append(toIndentedString(dateCompleted)).append("\n");
		sb.append("    dateRevised: ").append(toIndentedString(dateRevised)).append("\n");
		sb.append("    article: ").append(toIndentedString(article)).append("\n");
		sb.append("    medlineJournalInfo: ").append(toIndentedString(medlineJournalInfo)).append("\n");
		sb.append("    citationSubset: ").append(toIndentedString(citationSubset)).append("\n");
		sb.append("    meshHeadingList: ").append(toIndentedString(meshHeadingList)).append("\n");
		sb.append("    keywordList: ").append(toIndentedString(keywordList)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
