/*
 * JournDoc Downloader Client API
 * This is a journdoc downloader client
 *
 * OpenAPI spec version: 1.0.0
 * Contact: david@dskow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.dskow.downloader.models.client;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * PubmedArticleSetC
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-26T09:41:10.684-04:00")
public class PubmedArticleSetC {
	@SerializedName("pubmedArticle")
	private PubmedArticle pubmedArticle = null;

	public PubmedArticleSetC pubmedArticle(PubmedArticle pubmedArticle) {
		this.pubmedArticle = pubmedArticle;
		return this;
	}

	/**
	 * A header
	 * 
	 * @return pubmedArticle
	 **/
	@ApiModelProperty(example = "null", value = "A header")
	public PubmedArticle getPubmedArticle() {
		return pubmedArticle;
	}

	public void setPubmedArticle(PubmedArticle pubmedArticle) {
		this.pubmedArticle = pubmedArticle;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		PubmedArticleSetC pubmedArticleSet = (PubmedArticleSetC) o;
		return Objects.equals(this.pubmedArticle, pubmedArticleSet.pubmedArticle);
	}

	@Override
	public int hashCode() {
		return Objects.hash(pubmedArticle);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class PubmedArticleSet {\n");

		sb.append("    pubmedArticle: ").append(toIndentedString(pubmedArticle)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
