/*
 * JournDoc Downloader Client API
 * This is a journdoc downloader client
 *
 * OpenAPI spec version: 1.0.0
 * Contact: david@dskow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.dskow.downloader.models.client;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * PubmedArticle
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-26T09:41:10.684-04:00")
public class PubmedArticle {
	@SerializedName("medlineCitation")
	private MedlineCitationC medlineCitation = null;

	@SerializedName("pubmedData")
	private PubmedDataC pubmedData = null;

	public PubmedArticle medlineCitation(MedlineCitationC medlineCitation) {
		this.medlineCitation = medlineCitation;
		return this;
	}

	/**
	 * A header
	 * 
	 * @return medlineCitation
	 **/
	@ApiModelProperty(example = "null", value = "A header")
	public MedlineCitationC getMedlineCitation() {
		return medlineCitation;
	}

	public void setMedlineCitation(MedlineCitationC medlineCitation) {
		this.medlineCitation = medlineCitation;
	}

	public PubmedArticle pubmedData(PubmedDataC pubmedData) {
		this.pubmedData = pubmedData;
		return this;
	}

	/**
	 * A header
	 * 
	 * @return pubmedData
	 **/
	@ApiModelProperty(example = "null", value = "A header")
	public PubmedDataC getPubmedData() {
		return pubmedData;
	}

	public void setPubmedData(PubmedDataC pubmedData) {
		this.pubmedData = pubmedData;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		PubmedArticle pubmedArticle = (PubmedArticle) o;
		return Objects.equals(this.medlineCitation, pubmedArticle.medlineCitation)
				&& Objects.equals(this.pubmedData, pubmedArticle.pubmedData);
	}

	@Override
	public int hashCode() {
		return Objects.hash(medlineCitation, pubmedData);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class PubmedArticle {\n");

		sb.append("    medlineCitation: ").append(toIndentedString(medlineCitation)).append("\n");
		sb.append("    pubmedData: ").append(toIndentedString(pubmedData)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
