/*
 * JournDoc Downloader Client API
 * This is a journdoc downloader client
 *
 * OpenAPI spec version: 1.0.0
 * Contact: david@dskow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.dskow.downloader.models.client;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * SearchResultC
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-26T09:41:10.684-04:00")
public class SearchResultC {
	@SerializedName("count")
	private String count = null;

	@SerializedName("retmax")
	private String retmax = null;

	@SerializedName("retstart")
	private String retstart = null;

	@SerializedName("idlist")
	private List<String> idlist = new ArrayList<String>();

	@SerializedName("translationset")
	private List<TranslationsetItemC> translationset = new ArrayList<TranslationsetItemC>();

	@SerializedName("translationstack")
	private List<Object> translationstack = new ArrayList<Object>();

	@SerializedName("querytranslation")
	private String querytranslation = null;

	@SerializedName("errorlist")
	private FetchErrorListC errorlist = null;

	@SerializedName("warninglist")
	private FetchWarningListC warninglist = null;

	public SearchResultC count(String count) {
		this.count = count;
		return this;
	}

	/**
	 * A fetch count
	 * 
	 * @return count
	 **/
	@ApiModelProperty(example = "null", value = "A fetch count")
	public String getCount() {
		return count;
	}

	public void setCount(String count) {
		this.count = count;
	}

	public SearchResultC retmax(String retmax) {
		this.retmax = retmax;
		return this;
	}

	/**
	 * The fetch ret max
	 * 
	 * @return retmax
	 **/
	@ApiModelProperty(example = "null", value = "The fetch ret max")
	public String getRetmax() {
		return retmax;
	}

	public void setRetmax(String retmax) {
		this.retmax = retmax;
	}

	public SearchResultC retstart(String retstart) {
		this.retstart = retstart;
		return this;
	}

	/**
	 * The fetch ret start
	 * 
	 * @return retstart
	 **/
	@ApiModelProperty(example = "null", value = "The fetch ret start")
	public String getRetstart() {
		return retstart;
	}

	public void setRetstart(String retstart) {
		this.retstart = retstart;
	}

	public SearchResultC idlist(List<String> idlist) {
		this.idlist = idlist;
		return this;
	}

	public SearchResultC addIdlistItem(String idlistItem) {
		this.idlist.add(idlistItem);
		return this;
	}

	/**
	 * The fetch id list
	 * 
	 * @return idlist
	 **/
	@ApiModelProperty(example = "null", value = "The fetch id list")
	public List<String> getIdlist() {
		return idlist;
	}

	public void setIdlist(List<String> idlist) {
		this.idlist = idlist;
	}

	public SearchResultC translationset(List<TranslationsetItemC> translationset) {
		this.translationset = translationset;
		return this;
	}

	public SearchResultC addTranslationsetItem(TranslationsetItemC translationsetItem) {
		this.translationset.add(translationsetItem);
		return this;
	}

	/**
	 * The fetch translation set
	 * 
	 * @return translationset
	 **/
	@ApiModelProperty(example = "null", value = "The fetch translation set")
	public List<TranslationsetItemC> getTranslationset() {
		return translationset;
	}

	public void setTranslationset(List<TranslationsetItemC> translationset) {
		this.translationset = translationset;
	}

	public SearchResultC translationstack(List<Object> translationstack) {
		this.translationstack = translationstack;
		return this;
	}

	public SearchResultC addTranslationstackItem(Object translationstackItem) {
		this.translationstack.add(translationstackItem);
		return this;
	}

	/**
	 * The fetch translation set
	 * 
	 * @return translationstack
	 **/
	@ApiModelProperty(example = "null", value = "The fetch translation set")
	public List<Object> getTranslationstack() {
		return translationstack;
	}

	public void setTranslationstack(List<Object> translationstack) {
		this.translationstack = translationstack;
	}

	public SearchResultC querytranslation(String querytranslation) {
		this.querytranslation = querytranslation;
		return this;
	}

	/**
	 * The fetch query translation
	 * 
	 * @return querytranslation
	 **/
	@ApiModelProperty(example = "null", value = "The fetch query translation")
	public String getQuerytranslation() {
		return querytranslation;
	}

	public void setQuerytranslation(String querytranslation) {
		this.querytranslation = querytranslation;
	}

	public SearchResultC errorlist(FetchErrorListC errorlist) {
		this.errorlist = errorlist;
		return this;
	}

	/**
	 * The fetch error list
	 * 
	 * @return errorlist
	 **/
	@ApiModelProperty(example = "null", value = "The fetch error list")
	public FetchErrorListC getErrorlist() {
		return errorlist;
	}

	public void setErrorlist(FetchErrorListC errorlist) {
		this.errorlist = errorlist;
	}

	public SearchResultC warninglist(FetchWarningListC warninglist) {
		this.warninglist = warninglist;
		return this;
	}

	/**
	 * The fetch warning list
	 * 
	 * @return warninglist
	 **/
	@ApiModelProperty(example = "null", value = "The fetch warning list")
	public FetchWarningListC getWarninglist() {
		return warninglist;
	}

	public void setWarninglist(FetchWarningListC warninglist) {
		this.warninglist = warninglist;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		SearchResultC searchResultC = (SearchResultC) o;
		return Objects.equals(this.count, searchResultC.count) && Objects.equals(this.retmax, searchResultC.retmax)
				&& Objects.equals(this.retstart, searchResultC.retstart)
				&& Objects.equals(this.idlist, searchResultC.idlist)
				&& Objects.equals(this.translationset, searchResultC.translationset)
				&& Objects.equals(this.translationstack, searchResultC.translationstack)
				&& Objects.equals(this.querytranslation, searchResultC.querytranslation)
				&& Objects.equals(this.errorlist, searchResultC.errorlist)
				&& Objects.equals(this.warninglist, searchResultC.warninglist);
	}

	@Override
	public int hashCode() {
		return Objects.hash(count, retmax, retstart, idlist, translationset, translationstack, querytranslation,
				errorlist, warninglist);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class SearchResultC {\n");

		sb.append("    count: ").append(toIndentedString(count)).append("\n");
		sb.append("    retmax: ").append(toIndentedString(retmax)).append("\n");
		sb.append("    retstart: ").append(toIndentedString(retstart)).append("\n");
		sb.append("    idlist: ").append(toIndentedString(idlist)).append("\n");
		sb.append("    translationset: ").append(toIndentedString(translationset)).append("\n");
		sb.append("    translationstack: ").append(toIndentedString(translationstack)).append("\n");
		sb.append("    querytranslation: ").append(toIndentedString(querytranslation)).append("\n");
		sb.append("    errorlist: ").append(toIndentedString(errorlist)).append("\n");
		sb.append("    warninglist: ").append(toIndentedString(warninglist)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
