/*
 * JournDoc Downloader Client API
 * This is a journdoc downloader client
 *
 * OpenAPI spec version: 1.0.0
 * Contact: david@dskow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.dskow.downloader.models.client;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * TranslationStackItemC
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-26T09:41:10.684-04:00")
public class TranslationStackItemC {
  @SerializedName("term")
  private String term = null;

  @SerializedName("field")
  private String field = null;

  @SerializedName("count")
  private String count = null;

  @SerializedName("explode")
  private String explode = null;

  public TranslationStackItemC term(String term) {
    this.term = term;
    return this;
  }

   /**
   * A translation stack term
   * @return term
  **/
  @ApiModelProperty(example = "null", value = "A translation stack term")
  public String getTerm() {
    return term;
  }

  public void setTerm(String term) {
    this.term = term;
  }

  public TranslationStackItemC field(String field) {
    this.field = field;
    return this;
  }

   /**
   * A translation stack field
   * @return field
  **/
  @ApiModelProperty(example = "null", value = "A translation stack field")
  public String getField() {
    return field;
  }

  public void setField(String field) {
    this.field = field;
  }

  public TranslationStackItemC count(String count) {
    this.count = count;
    return this;
  }

   /**
   * A translation stack count
   * @return count
  **/
  @ApiModelProperty(example = "null", value = "A translation stack count")
  public String getCount() {
    return count;
  }

  public void setCount(String count) {
    this.count = count;
  }

  public TranslationStackItemC explode(String explode) {
    this.explode = explode;
    return this;
  }

   /**
   * The translation stack explode
   * @return explode
  **/
  @ApiModelProperty(example = "null", value = "The translation stack explode")
  public String getExplode() {
    return explode;
  }

  public void setExplode(String explode) {
    this.explode = explode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TranslationStackItemC translationStackItemC = (TranslationStackItemC) o;
    return Objects.equals(this.term, translationStackItemC.term) &&
        Objects.equals(this.field, translationStackItemC.field) &&
        Objects.equals(this.count, translationStackItemC.count) &&
        Objects.equals(this.explode, translationStackItemC.explode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(term, field, count, explode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TranslationStackItemC {\n");
    
    sb.append("    term: ").append(toIndentedString(term)).append("\n");
    sb.append("    field: ").append(toIndentedString(field)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    explode: ").append(toIndentedString(explode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

